apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:

      imagePullSecrets:
        - name: ghcr-secret

      initContainers:
      - name: wait-for-mongo
        image: busybox:1.36
        command:
          - sh
          - -c
          - until nc -z mongo 27017; do echo waiting for mongo; sleep 2; done;

      containers:
      - name: backend
        image: ghcr.io/anjumsardar/backend-image:v1

        ports:
        - containerPort: 8000

        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: MONGO_URI

        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 5

        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 20
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000